apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-app
spec:
  type: {{ .Values.mongodb.service.type}}
  selector:
    app: mongodb-app
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port}}
      targetPort: {{ .Values.mongodb.service.port}}    